#!/bin/bash
#SBATCH --job-name=sfe_111
#SBATCH --ntasks=16
#SBATCH --cpus-per-task=1
#SBATCH --time=10:00:00
#SBATCH --error=slurm-%j.stderr
#SBATCH --output=slurm-%j.stdout

module restore set-gap

lmp=lmp_mpi
a1=2.833612
module restore set-gap
mpirun -np 16 $lmp -in in.sfe_111 -v lat $a1
