#!/bin/bash
#SBATCH --job-name=sfe_112
#SBATCH --ntasks=16
#SBATCH --cpus-per-task=1
#SBATCH --time=10:00:00
#SBATCH --error=slurm-%j.stderr
#SBATCH --output=slurm-%j.stdout

lmp=$1
a1=$2
module restore set-gap
mpirun -np 16 $lmp -in in.sfe_112 -v lat $a1
